### ISSUE TITLE
Editing layout.

### ISSUE THREAD

**Issue by syto203** [iNDS-Team/iNDS#10]
In landscape mode on the iPhone X editing the layout is missing the size adjustment bar at the bottom, it’s present in portrait but not in landscape.
on iOS 11.2.6

Edit: on smaller screen devices the size adjustment bar is missing from both portrait and landscape.
Devices tested iphone 6 and iphone 8 running ios 11.1.2 and 11.3 respectively.

**Comment by FrederickGeek8** [comment]
I saw this commit by @DarkRedFish a while ago that I think addresses this issue. It might be a *starting* point for a fix. https://github.com/DarkRedFish/iNDS/commit/b313f94c2090a003cbb0ac6b542975bcb5f5e328

I'll submit something soon, but if someone wants to take this up it would be a good first issue I think.

**Comment by syto203** [comment]
i've created a couple of landscape layouts for the iPhone X until it's fixed.
[Layouts.zip](https://github.com/iNDS-Team/iNDS/files/2024411/Layouts.zip)
