### ISSUE TITLE
Cannot use iNDS with iTunes after installing iNDS from official Cydia repo on iOS 12 unc0ver jailbreak.

### ISSUE THREAD

**Issue by DrConflict** [iNDS-Team/iNDS#100]
So after I installed unc0ver beta 46 I was excited to install iNDS from the official Cydia repo. 
Sadly I came to the conclusion that if I was install iNDS via the official cydia repo I can't save games or save "states". I also can't transfer games to app in iTunes, it just keeps showing the rotating circle.
I'm on iOS 12.1.1 and unc0ver beta 46. The weird thing is that when I install iNDS via cydia impactor 
with Apple account The app works as normal but I have to resign every 7 days. I hope this can be fixed soon.

**To Reproduce**
1. install unc0ver jailbreak beta 46
2. install latest iNDS from official cydia repo.
3. Try to install games via iTunes as usual.

**Expected behavior**
Not able to save in game and states, cannot transfer games via itunes' file sharing option..

**Smartphone (please complete the following information):**
 - Device: ipad 2018
 - OS: iOS 12.1.1
 - Browser Chrome
 - Version 73

**Comment by syto203** [comment]
Check the permissions on your /var/mobile/Documents directory and on var/mobile/Documents/iNDS the ownership must be mobile:mobile

**Comment by DrConflict** [comment]
> Check the permissions on your /var/mobile/Documents directory and on var/mobile/Documents/iNDS the ownership must be mobile:mobile

Already did this in Filza. Although there is no iNDS folder at var/mobile/Documents/iNDS, only at private/var/mobile/Documents/iNDS. Not sure what to do at this point to be honest. I can drag and drop games to the file sharing in iTunes but games are not detected in iNDS.

**Comment by FrederickGeek8** [comment]
Closing as the issue appears to be resolved. Perhaps this would make a good addition to a troubleshooting guide.
