### ISSUE TITLE
Microphone Problems for AAI2

### ISSUE THREAD

**Issue by NobodyCares13** [iNDS-Team/iNDS#101]
Hey all, im having some problems with the microphone feature for Ace Attorney Investigations 2, and I was wondering if I could get some help. So the problem is, is that the microphone will not stop blowing, Ive tried turning the microphone off and on, Ive searched all around but haven’t found anything. I need the mircophone to stop blowing to progress, by any means, please help, it would be greatly appreciated.

**Comment by FrederickGeek8** [comment]
What version of iNDS are you running?

**Comment by NobodyCares13** [comment]
Ver. 1.9.1

**Comment by FrederickGeek8** [comment]
Microphone support was fixed in version 1.10.2. Try that version!

**Comment by NobodyCares13** [comment]
Okay I check it out and see

**Comment by NobodyCares13** [comment]
Wait can you tell me how to download 1.10.2? Im not sure how to do it.

**Comment by FrederickGeek8** [comment]
You can check our wiki for [jailbroken devices](https://github.com/iNDS-Team/iNDS/wiki/Building-&-Installing-iNDS-(Jailbroken)#option-1-cydia) and [jailed devices](https://github.com/iNDS-Team/iNDS/wiki/Building-&-Installing-iNDS-(Jailed)#third-party). I'm not sure how you installed it initially, but if it was through another service (that you want to stay with), you can contact their support team and point them to this repository.

**Comment by FrederickGeek8** [comment]
I'm closing this issue because the microphone issues should be fixed in the latest iNDS. I can reopen it later if need be.
