### ISSUE TITLE
Advance Wars Visual bug

### ISSUE THREAD

**Issue by EthanYDTang** [iNDS-Team/iNDS#104]
**Describe the bug**
In Advance Wars Dual Strike, the cursor displaying the currently selected space is missing.

**To Reproduce**
1. Use iNDS from HEAD
2. Start any game (Campaign, Versus, War Room)
3. Cursor will be missing

**Expected behavior**
A cursor should highlight the currently selected space.

**Screenshots**
![IMG_0003](https://user-images.githubusercontent.com/49821771/57171602-724d4a00-6dca-11e9-8b8e-0077b45aae3d.PNG)

**Device**
 - Device: ipad mini 5
 - OS: ios 12.2

**Additional context**
This is a known issue in desmume, and is an easy fix by adjusting depth comparison threshold to a larger number. However, iNDS lacks such an option.

**Comment by FrederickGeek8** [comment]
I'll look into adding a depth comparison adjustment setting!
