### ISSUE TITLE
Audio Routing thru Phone instead of speakers.

### ISSUE THREAD

**Issue by syto203** [iNDS-Team/iNDS#11]
on every app launch the default audio route is always the phone instead of speakers.
you need to open control center and choose the speakers as the output.
after killing the app and relaunching you need to re-set again.

**Comment by FrederickGeek8** [comment]
I can't get your workaround to work with Bluetooth speakers (on iOS 11.4), however, with wired headphones, everything seems to work as expected.

**Comment by FrederickGeek8** [comment]
Sorry, if I didn't understand the issue. I was browsing the Traffic data and found a Reddit thread that said that the audio was being routed through the earpiece instead of the phone speakers, is this still the case?
