### ISSUE TITLE
It’s been fine for a while but it asks me to verify

### ISSUE THREAD

**Issue by XuanXuan10** [iNDS-Team/iNDS#117]
iPad, iOS 12.2
![9D5648A2-908D-4248-87EF-99FC03143B08](https://user-images.githubusercontent.com/52178309/60049003-59ab3300-969b-11e9-921b-d452a0c23ac5.png)
![8926010A-E096-4722-8996-FD4B47D17CD8](https://user-images.githubusercontent.com/52178309/60049004-59ab3300-969b-11e9-9f9e-84c544ddde5f.png)
It worked fine for a while but now it’s doing the thing again, and it doesn’t have an option to verify.

**Comment by FrederickGeek8** [comment]
How did you install iNDS?

**Comment by XuanXuan10** [comment]
iemulator
![9A47A924-0CF7-4A6E-B6A7-0B3D4F61538C](https://user-images.githubusercontent.com/52178309/60054947-0be9f700-96aa-11e9-84a0-a80740710d7f.png)
![107BC329-8D95-4A3C-B395-0FDD1D71A31D](https://user-images.githubusercontent.com/52178309/60054948-0be9f700-96aa-11e9-9320-c43d2c514025.png)

**Comment by mpoyer** [comment]
I downloaded from tweakbox and had the same issue. I had to delete it and redownload to get it to work again. Unfortunately I didn’t sync to Dropbox and lost all of my saves. I tried extracting them to my CP through iTunes but the saves were in a folder called ‘battery’ and I couldn’t for the life of me get it to open, copy, move or do anything to save them. Had to restart pokemon diamond after 12 hours and half of the game beaten

**Comment by mrlotusss** [comment]
XuanXuan ơi. Mình k thể down đc iNDS từ bất cứ trang nào được. Ấn down nó cứ hiện app lên được 1s rồi biến mất luôn. Mình đang dùng ios 12.3.1. Thử mấy hôm nay rồi mà ko đc. B biết cách fix ko ?

**Comment by FrederickGeek8** [comment]
I believe this is a problem with third-party distributors and not an issue with iNDS itself. 

@mpoyer given the way that iTunes deals with folder, you need to drag the folder out of iTunes in order to browse it. There is no way to browse the folder or replace anything in iTunes without dragging out the folder, replacing everything inside, then dragging back to iTunes.
