### ISSUE TITLE
Prebuilt IPA

### ISSUE THREAD

**Issue by FrederickGeek8** [iNDS-Team/iNDS#12]
Some users have requested (#9) that pre-built IPA's be included in the Release section on Github. Although we cannot at this time provide signed IPA's (for a number of reasons), we can provide unsigned IPA's that should (if my understanding is correct) be able to be sideloaded through Cydia Impactor.

I am looking for some users to do some testing with prebuilt IPA's before I start posting them on the Releases page. Please post below if you have an interested in this.

**Comment by syto203** [comment]
i'm in as always

**Comment by Wh0ba** [comment]
Count me in too
I can install it on my jailbroken 5s 
Using `appinst` With the help from `AppsyncUnified` to sign the apps

**Comment by FrederickGeek8** [comment]
I am currently looking for people to test! [Please pop into the Gitter chat when you are available to help out.](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by FrederickGeek8** [comment]
I think the goal of this Issue has been achieved. It can be reopened if need be.
