### ISSUE TITLE
I can't download iNDS 

### ISSUE THREAD

**Issue by mrlotusss** [iNDS-Team/iNDS#121]
My iphone is ios 12.3.1 
And i can't download iNDS on tweakboxapp, iemulator, or any website other . When i click download, the app shows up, then disappears. 
Help me please :(

**Comment by syto203** [comment]
They have been revoked. You can either sideload the app yourself using cydia impactor, wait until they renew their license or  subscribe to a paid service. In any case this isn’t an issue concerning iNDS itself. Good luck
