### ISSUE TITLE
how do i close lid?

### ISSUE THREAD

**Issue by ylva23** [iNDS-Team/iNDS#123]
hi there, ive got version 1.9.1 of inds on my iphone 8+ i cannot for the life of me work out how to close the lid, earlier in the game i was playing (hotel dusk room 215) i manage to get it to happen but i have NO clue how, i just shook my phone and spammed my lock and home buttons, but i cant seem to get it to trigger now. ive spent 45 mins googling everything and i cant find anything that says how to do it

pls help it will be greatly appreciated <3

**Comment by FrederickGeek8** [comment]
Currently, there is no option to close the lid. Your best bet is to transfer your files to DeSmuME on your computer and perform the lid close there. This enhancement is being tracked in #107, but it looks like it will be a tricky thing to implement given that the current implementation is broken.

**Comment by ylva23** [comment]
how do i do that?

**Comment by FrederickGeek8** [comment]
I created a guide for you in the Wiki. Please let me know if you need any help. https://github.com/iNDS-Team/iNDS/wiki/Transferring-Saves-to-DeSmuME
