### ISSUE TITLE
iNDS Crash on Startup

### ISSUE THREAD

**Issue by JuicyPickle** [iNDS-Team/iNDS#124]
Only in the last hour, whenever I try and open the iNDS app, the logo will pop up and then the app will crash.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
- iOS 12.4
Non- Jailbroken
Downloaded from BuildStore
Version 1.10.3

**Comment by pkluver944** [comment]
Same happens to me! I tried to launch it and it kept crashing. Tried reinstalling the latest version and it did nothing. I use an iPhone SE

**Comment by Utonnii** [comment]
hello yesterday and today my emulator iNds close when i want open it and say impossible to chech the app, so i go to setting and i want check the app but nothing is do, i don't understand this problem any solutions for solve this?

**Comment by FrederickGeek8** [comment]
I believe these problems are all due to the signing privileges being revoked of the services you have used to download iNDS; I assume you all downloaded it from a third-party source. Please contact where you downloaded it from to resolve the issue.
