### ISSUE TITLE
A night theme (with support for dark mode on iOS 13)

### ISSUE THREAD

**Issue by pcgamer31098** [iNDS-Team/iNDS#129]
**Is your feature request related to a problem? Please describe.**
The user interface is too bright when using the app at night.

**Describe the solution you'd like**
There should be a night theme for the app, preferably one that will work with the dark mode in the upcoming iOS 13.

**Describe alternatives you've considered**
I don't have any alternatives.

**Additional context**
I don't have any additional information.

**Comment by DrConflict** [comment]
Yes please, I second this. iNDS is still the greatest NDS emulators on iOS, so this addition would be nice.

**Comment by FrederickGeek8** [comment]
Should be fixed in 68279f5c4f5f91343bc7b51bb45dc90bde2639c3. Let me know if I missed anything. I'll roll out an update soon.

**Comment by FrederickGeek8** [comment]
Version 1.10.7 has been released that addresses this issue: https://github.com/iNDS-Team/iNDS/releases/tag/v1.10.7

There are still some things that could be changed, but in general Dark Mode works throughout the app.
