### ISSUE TITLE
Present on Xcode 11 & iOS 13

### ISSUE THREAD

**Issue by rabehssera** [iNDS-Team/iNDS#132]
**Describe the bug**
The game selection view controller, and the DS emulator don't appear on Full Screen, but as the new "modal" standard for iOS 13

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 13

**Additional context**
Only happens when the app is compiled with Xcode 11.

(As a developer, I'm gonna try to work on it myself)

**Comment by zinkuro** [comment]
Just add this line into the AppDelegate.m, after the vc is created:

**emulatorViewController.modalPresentationStyle = 0;**

[rootViewController presentViewController:emulatorViewController animated:YES completion:nil];

**Comment by FrederickGeek8** [comment]
Thanks! I'll integrate this ASAP. PR's are accepted too :)

**Comment by rabehssera** [comment]
I made a PR : #141

**Comment by FrederickGeek8** [comment]
That PR has been accepted and is now available in version 1.10.4.
