### ISSUE TITLE
App crashed when clicking on the setting button.

### ISSUE THREAD

**Issue by zinkuro** [iNDS-Team/iNDS#134]
**Describe the bug**
App crashed

**To Reproduce**
1. Running a rom
2. Click on the setting button
3. Crashed

**Expected behavior**
when running at debug-mode, i add a breakpoint to see what's the problem;
the breakpoint break at line.883 in 'iNDSEmulatorViewController.mm':
```statusBar = [object valueForKey:key];```

here is the log:

```Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.```

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS 13.1
 - iNDS Version: 1.10.3

**Additional context**
in iOS 13, UIApplication could not get the statusBar by using key path"_statusBar", 
they give us  a new class "UIStatusBarManager" instead;

**Comment by XanderPSON** [comment]
I'm encountering this as well. It means I can't change the button layout, which is making some games unplayable on iOS 13, since the buttons are located off the screen.

**Comment by FrederickGeek8** [comment]
This was fixed in #141. Correct me if I'm wrong.
