### ISSUE TITLE
Drop box sync always fails 

### ISSUE THREAD

**Issue by killluas** [iNDS-Team/iNDS#135]
no matter what I do drop box always fails to sync, using INDS from ignition. I sign in and out to see and it fixes problem but nope nothing always get the sync failed

**Comment by FrederickGeek8** [comment]
Can you provide what iOS version you are running, as well as what version of iNDS?

**Comment by killluas** [comment]
iOS 13.1.2 and INDS 1.10.3

**Comment by sowderca** [comment]
I’m encountering this issue as well.  Same versions as @killluas.

**Comment by FrederickGeek8** [comment]
For those available to help, the error that is causing the Dropbox sync to fail is:
```
DropboxClientError[{
    NSError = "Error Domain=NSCocoaErrorDomain Code=513 \"\U201cCFNetworkDownload_sciIzu.tmp\U201d couldn\U2019t be moved because you don\U2019t have permission to access \U201ctmp\U201d.\" UserInfo={NSSourceFilePathErrorKey=/var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/net.nerd.iNDS/CFNetworkDownload_sciIzu.tmp, NSUserStringVariant=(\n    Move\n), NSDestinationFilePath=/private/var/mobile/Containers/Data/Application/920D021E-717A-4DFE-862A-F9BAFFB7D0EE/tmp/2C7C2B3E-4A25-4054-9524-38B3B17D0F87, NSFilePath=/var/mobile/Library/Caches/com.apple.nsurlsessiond/Downloads/net.nerd.iNDS/CFNetworkDownload_sciIzu.tmp, NSUnderlyingError=0x2809dfc90 {Error Domain=NSPOSIXErrorDomain Code=1 \"Operation not permitted\"}}";
}];
```
It occurs when using `DBFILESUserAuthRoutes`'s `downloadUrl` function (used in CHBgDropboxSync.mm:266)

**Comment by Barnetta45** [comment]
I am having the same issue since the licenses from the Build Store got revoked a couple of days ago and I had to reinstall the app. No matter what I do the Dropbox sync won’t work. I even downloaded and tried out the Delta app just to see if it had something to do with my Dropbox app but it worked perfectly. Please help 🙏🏽

iOS 13.1.2 version and iNDS 1.10.3

**Comment by Degstorm1** [comment]
I'm having the same issue I'm running iOS 13.1.2 and I tried older and newer versions of inds but Dropbox sync still seems to fail.
Please get this fixed!! or any help is appreciated too🙏🏽

**Comment by emotionstudy4** [comment]
I’m having the same issue as those above, using Build Store and iPad 13.1.2

**Comment by lazulienoshima** [comment]
I'm having the same issue as everyone else, using Ignition with an iPad with iOS 13.1.2 . I'm pretty sure it has to do with iOS 13. I really hope the iNDS-team look into this problem soon.

**Comment by Blade7055** [comment]
I’m using the same inds version but ios 13.1.3 and am having the same problem. It’s so frustrating because I want to play Pokémon Soul Silver and even though the game runs and sounds great I can’t make save anything I do so I can’t make any significant progress in the game.

**Comment by killluas** [comment]
Is this ever gonna get fixed?

**Comment by FrederickGeek8** [comment]
Sorry for this not getting done. I still am unable to figure out what is causing the errors. I might raise an issue with Dropbox to me it seems like its a problem on their end. I'll continue testing things this weekend.

Interestingly, it does not have this issue when running inside of the simulator, only on the physical device.

**Comment by FrederickGeek8** [comment]
I was able to fix it. I'll be posting a new version today.
