### ISSUE TITLE
Not verified

### ISSUE THREAD

**Issue by wai015** [iNDS-Team/iNDS#137]
The apps and the developer are said to be not verified. Verfication is failed.

**To Reproduce**
1. Go to ‘setting’
2. Click on ‘profile’
3. Click on ‘verify apps’

**Expected behavior**
No verfication is competed even clicked.

**Desktop
iOS 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 12.1.4

**Comment by SarahH12099** [comment]
This has nothing to do with iNDS at all, you have to contact the signing service you got iNDS from, not here.
