### ISSUE TITLE
TestFlight 

### ISSUE THREAD

**Issue by starraiderx** [iNDS-Team/iNDS#138]
**Is your feature request related to a problem? Please describe.**
Revokes 
**Describe the solution you'd like**
A TestFlight version for the app 
**Describe alternatives you've considered**

**Additional context**

**Comment by FrederickGeek8** [comment]
I assume you meant to ask about whether I could start a Testflight for iNDS. There are two issues with this idea:
1. Right now we don't have any contributors on Open Collective. What this means is that I do not have the money to open up another Apple Developer account specifically for iNDS.
2. I believe that Testflight applications go through an initial verification process by Apple. Given that this is not an application allowed by the App Store, I doubt it would pass the verification.
