### ISSUE TITLE
iNDS Dropbox Sync Error iOS 13

### ISSUE THREAD

**Issue by lazulienoshima** [iNDS-Team/iNDS#139]
Hello, i've been using iNDS for quite some time, but recently i've updated my iPAD to iOS 13 and ever since I could not sync iNDS to my dropbox anymore and get my save files back. It's very annoying and i've seen a lot of people are having the same issue lately too.

1. Open iNDS
2. Click on Settings
3. Click on Dropbox
4. Link account and enable Dropbox
5. Dropbox starts syncing
6. “Failed to sync” pops up on the screen

I expected it to say “Syncing complete!” and then to see all my save files being back in my rom.

 
![image](https://user-images.githubusercontent.com/56702073/67051812-800a4800-f13c-11e9-8a29-47633308b2fd.jpeg)

 - OS: iOS 13.1.2
 - iNDS Version: 1.10.3
 - Device: iPad Air 2

I hope this problem can be resolved as quick as possible, as I really enjoy playing on iNDS. Thank you.

**Comment by qfaq** [comment]
I've currently found that connecting your phone to your computer, and then using iTunes to get the save data works pretty well.

**Comment by FrederickGeek8** [comment]
Please see #135 for updates.
