### ISSUE TITLE
Buttons Overlay Edge Maping

### ISSUE THREAD

**Issue by syto203** [iNDS-Team/iNDS#14]
placing buttons near the edge of the screen renders the parts closest to the edge unresponsive.

**to reproduce**:
- edit layout
- move the D-Pad or any button to the edge of the screen
- save the layout
- now start a ROM and try pressing the button touching the edge

Edit: for now this is an iPhone X only issue. i believe it's been caused by supporting the iphone X resolution and while it worked well with other elements it seems that resizing the buttons only increased their visuals and not their respective mapping.

**Comment by FrederickGeek8** [comment]
I believe I've been able to reproduce this in the past on my iPhone X. What platform / version are you running? Bug Report templates are there for a reason 👍

**Comment by syto203** [comment]
this is universal not iDevice specific that's why i didnt include it.

**Comment by FrederickGeek8** [comment]
I think this is just an iPhone X problem. Especially with the advent of "Safe Area", placing elements outside of the safe area is really something that iNDS should be held accountable for.
