### ISSUE TITLE
Cover Art Missing

### ISSUE THREAD

**Issue by syto203** [iNDS-Team/iNDS#15]
as of iNDS v1.7.0
 on iPhone X the ROMs cover art is missing.
 on i6, i8 the cover art is working. [i6 Cover Art](https://i.imgur.com/UXzgmOV.png)

**Comment by brand175** [comment]
The cover art is also missing on my iPad Pro 9.7 inch (2015 model) on iNDS v1.7.1.

**Comment by FrederickGeek8** [comment]
@syto203 What iOS Versions, etc are you running on your iPhone 6 and 8? I'm trying to run it on iPhone 6 but I'm running into the same issue. Seeing as you are reporting that it is working on a physical device, it seems to be an iOS versioning issue...

**Comment by FrederickGeek8** [comment]
Just a quick FYI! I may have shot myself in the foot here, but since around 1.7.1 (4744e21 to be exact), the system doesn't even try to add the cover art. In order to try and fix this issue, or at the very least debug it, you have to first uncomment [line 164 and 173 in iNDSROMTableViewController.m](https://github.com/iNDS-Team/iNDS/blob/v1.7.2/iNDS/roms/iNDSROMTableViewController.m#L164).

**Comment by FrederickGeek8** [comment]
Just a quick update before I go to work for the day! Last night I was able to get the icon to appear on modern OSes (11.2+), however, only intermittently. You can check out my fork at [FrederickGeek8/iNDS/tree/fix-cover](https://github.com/FrederickGeek8/iNDS/tree/fix-cover). Currently, every couple of launches, the icon for the game will become white or corrupted.

[It appears that with iOS 11.2, Apple made some unannounced changes to Core Graphics, and broke a lot of code for people](https://github.com/rs/SDWebImage/issues/2130) (this is one of many such related posts), as a result, there are some tweaks to the icon generation code that needed to be made. I'm not sure what is causing the current icon corruption in my fork, but hopefully, it should be resolved soon.

**Comment by FrederickGeek8** [comment]
I'm not sure if I should publish my changes as is. I'm still not sure why I'm seeing such inconsistent results and whether it would be better to have intermittent cover art over no cover art.

**Comment by FrederickGeek8** [comment]
When stepping through the code, I noticed that `iNDSGame.m` is generating a valid `UIImage` (it is viewable in the Xcode debugger), however, it is displayed as a corrupted image on my device.

**Comment by FrederickGeek8** [comment]
I posted this in the Gitter chat earlier and I would love some feedback from the community on this idea:

> In reference to #15 (Cover Art Missing), how would people feel about a online (but cached) solution using [OpenVGDB](https://github.com/OpenVGDB/OpenVGDB/releases)? Right now I can’t seem to get the cover art to stabilize, and OpenVGDB would lend itself to a future redesign 😋
