### ISSUE TITLE
Unable to open dsv save file into my rom, legend of Zelda phantom hourglass

### ISSUE THREAD

**Issue by slaminsam45** [iNDS-Team/iNDS#151]
Essentially there is a point in the game in which you have to “close the ds” to solve a puzzle. Obviously this is impossible on iNDS so I exported out to desmume, and solved it and saved. For whatever reason now iNDS will not take the .dsv file that has the puzzle completed. An error pops up saying unknown file extension. The rom name and save name are the same, and it is a .dsv file. Any suggestions at all? I’m desperate.

**Comment by FrederickGeek8** [comment]
To me, it sounds like you are trying to directly share the DSV file with iNDS. You need to find some way to put it in the Battery folder in the iNDS application. You might want to refer to [the guide for transferring saves TO DeSmuME](https://github.com/iNDS-Team/iNDS/wiki/Transferring-Saves-to-DeSmuME#transferring-saves-to-computer) to know how to transfer saves. The only difference is that if you use iTunes (or Finder) you need to transfer the Battery folder off the device, replace the contents you want, then transfer it back.

Let me know if you have any further question or if this answered your question.

**Comment by slaminsam45** [comment]
Thanks so much for the help! I have one question. I am unable to use iTunes
to access files, because it seems like they removed the option to mess with
files. Would you know of a tutorial for how to get a version of iTunes that
allows this? Thanks.

**Comment by FrederickGeek8** [comment]
iTunes/Finder should still have this option. Drop me a message [over on Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and we'll figure it out.
