### ISSUE TITLE
Unable to Transfer Saves to DeSmuME

### ISSUE THREAD

**Issue by Calcio16** [iNDS-Team/iNDS#154]
I have tried to transfer saves to DeSmuME using iTunes, but the .dsv files don't appear and I am unable to open battery, which is where they should be. I have played the games and saved them using the in-game save, the save slot, and the pause. Then I plug my phone into my computer with a USB, open iTunes, click the device icon, and open File Sharing.
![iTunesTransfer](https://user-images.githubusercontent.com/8454065/72755103-ee6d0500-3b86-11ea-8a0a-948f7edbc516.PNG)
I have tried double clicking, right clicking, dragging, and copying and pasting the "Battery" file but nothing happened. I have also tried to use DropBox sync but when I open iNDS it always says "Syncing Started!" and then "Failed to Sync!"

I open iNDS by going to Settings -> Safari -> Clear History and Website Data. Then I go into Airplane mode with Wifi turned off and enter the app, turning off Airplane mode. This is usually the only method that works, with the exception being opening the app normally soon after exiting it.

**Desktop**
 - OS: 64-bit Windows 10
 - Browser Safari
 - Version 1903

**Smartphone:**
 - Device: iPhone XR
 - OS: iOS 13.3
 - Browser Safari
 - Version 13.3

I downloaded iNDS two weeks ago.

**Comment by FrederickGeek8** [comment]
So you've tried dragging the Battery folder to somewhere on your computer, replacing the files, then dragging it back? You might want to turn off Dropbox sync before doing this.

**Comment by FrederickGeek8** [comment]
Closed due to inactivity.
