### ISSUE TITLE
I can not see any roms after Version 1.10.7

### ISSUE THREAD

**Issue by veteransdr** [iNDS-Team/iNDS#159]
**Describe the bug**
I installed 1.10.6 via cydia repo 'https://inds.nerd.net/' and all ok.
But after I install 1.10.7 via 3Utools... somehow I got 2 inds on my homescreen. 
And even I copy roms to documents via 3Utools, itunes, ifunbox...and try to import from File app on iphne... there is no roms on 1.10.7 
Can anybody let me know where I can copy roms on 1.10.7?

**Smartphone (please complete the following information):**
 - Device:  iphone X
 - OS:iOS 13.3
 - Version 1.10.7

**Comment by sappykamen** [comment]
I had the same situations. For 1.10.7 the Roms are stored in /var/mobile/containers/data/application/iNDS/documents. 
On version 1.10.6 they were stored in a different path /var/mobile/documents/inds

Also just beware that on 1.10.7 I cannot get auto sync to Dropbox. So if I were you I would stay on 1.10.7 until that’s fixed if you care about cloud saves.
