### ISSUE TITLE
iNDS doesn't build in Xcode 11.4.1

### ISSUE THREAD

**Issue by cpshelton** [iNDS-Team/iNDS#172]
I get a build error when trying to build the latest version of iNDS in Xcode 11.4.1. The error is:

`Incompatible block pointer types sending 'void (^)(DBFILESMetadata * _Nullable __strong, DBFILESDeleteError * _Nullable __strong, DBRequestError * _Nullable __strong)' to parameter of type 'void (^ _Nonnull)(DBFILESDeleteResult * _Nullable __strong, DBFILESDeleteError * _Nullable __strong, DBRequestError * _Nullable __strong)'`

On line 288 of the file Main -> Dropbox -> CHBgDropboxSync.m

When I comment out lines 288 - 295, then the project builds successfully with no errors.

**Comment by FrederickGeek8** [comment]
Strange that this error cropped up. If you replace `DBFILESMetadata` with `DBFILESDeleteResult` it should work.

**Comment by cpshelton** [comment]
Thanks, this worked for me.
