### ISSUE TITLE
The website's certificate is expired?

### ISSUE THREAD

**Issue by Proaxel** [iNDS-Team/iNDS#173]
When you attempt to navigate to https://inds.nerd.net , or add it as a repo on a jailbroken iOS device, it returns a warning saying the website's certificate is invalid. Does that mean the website is dead?

**Comment by FrederickGeek8** [comment]
Whoops! Something went wrong. Let me investigate.

**Comment by FrederickGeek8** [comment]
It should be fixed now! Certbot decided to clobber my apache config again. Thanks for letting me know.

**Comment by Proaxel** [comment]
Alright, thanks for the quick response! Just an FYI, the website was like that for at least a week.
