### ISSUE TITLE
build doesn't compile

### ISSUE THREAD

**Issue by ywriterct** [iNDS-Team/iNDS#178]
**Describe the bug**
Hi I'm trying build the project locally on my phone. On clicking build, I get following issue:

Incompatible block pointer types sending 'void (^)(DBFILESMetadata * _Nullable __strong, DBFILESDeleteError * _Nullable __strong, DBRequestError * _Nullable __strong)' to parameter of type 'void (^ _Nonnull)(DBFILESDeleteResult * _Nullable __strong, DBFILESDeleteError * _Nullable __strong, DBRequestError * _Nullable __strong)'

**To Reproduce**
open project in xcode, try to build 
Running Xcode 11.5, building on iOS 13
<img width="871" alt="Screen Shot 2020-06-02 at 8 21 44 PM" src="https://user-images.githubusercontent.com/11013106/83582209-dcc14400-a50e-11ea-8b89-9a15cc2b67b5.png">

**Comment by FrederickGeek8** [comment]
This has already been solved in #172. I would really appreciate a pull request as I have been too busy recently to work on the project.
