### ISSUE TITLE
Dropbox Sync not working

### ISSUE THREAD

**Issue by Sekkio** [iNDS-Team/iNDS#18]
Hi, Dropbox sync isn't working. 
It's only able to sync all saves on the first time using the app. After reinstalling the app it loads the last game save, however, it does not sync newer game saves. Reinstalling the app does not load the latest game save but it shows the (latest) first game save. Now Dropbox only shows the same game save no matter how many times you reinstall the app. This can be reset by deleting the "inds" folder on dropbox if you delete the iNDS app first, though the same issues still apply afterwards. Simply, it only sync the game saves on the first usage of the app.

What I did:
1. Install INDS via cydia impactor
2. Turn on dropbox sync 
3 Import game and create game saves (via in-game save feature).
4 Delete and reinstall iNDS.
5. Turn on dropbox sync. (Sometimes I have to do it twice.)
6. Import game and check the save, it shows the latest/previous save from step 3.
7. Create a newer game save.
8. Delete and reinstall iNDS
9. Turn on dropbox sync. (Sometimes I have to do it twice.)
10. Import game and check the save, it does not show the latest/previous save from step 7, it shows the game save from step 3/6 instead of step 7.
11. Repeating 7-10 always shows the same results.

Device:
jailed ipad air 2
ios 11.2.1

Additional context:
Tested on iNDS 1.7.1 via github ipa and 1.7.0 via hollr2099 ipa. Used cydia impactor to install.
The game I tested on are Pokemon soul silver & Pokemon platinum (the nds are from theeye).
The issue may be the pokemon game, my dropbox account, dropbox or inds.

The only solution seems to be deleting "inds" folder in dropbox to re-sync after loading the game save each time you re-install the app. This didn't work though.
1. Install the app.
2. Turn on dropbox sync
3. Import game.
4. Load game save from dropbox.
5. Turn off dropbox sync  (it could be still syncing which may be why this didn't work)
5. Delete "inds" in dropbox.
6. Turn on dropbox sync.
7. Save game.
8. Repeat 1-7 each time you re-install the app.
However, it didn't work , I'm not sure why. 
It works if you delete iNDS app before "iNDS' folder but you will lose your game save.

**Comment by FrederickGeek8** [comment]
Hmm... Almost immediately after opening the iOS emulator I'm seeing a bug with the Dropbox sync I thought I fixed when developing the new Dropbox integration. Perhaps (likely) this is causing the behavior you are seeing. I will investigate and hopefully get back to you soon with a fix.

**Comment by FrederickGeek8** [comment]
I referenced the wrong issue in the PR 😓This issue is fixed by #21, not by #19
