### ISSUE TITLE
The app is revoked

### ISSUE THREAD

**Issue by CyanideX3** [iNDS-Team/iNDS#182]
On Saturday June 27,2020 the app is revoked and I can’t play any of my games. Keeps crashing. I hope I didn’t lose all my progress it would be a shame and when can we expect a update to fix this? Paid heavy money hope it wasn’t for nothing.

**Comment by FrederickGeek8** [comment]
I'm sorry to say that we have nothing to do with the distribution* and revocation of iNDS (nor did we get any of your money!) 
You should contact the service you purchased it through and have them fix it. Sorry we can't be of more help.

<small>*You can download iNDS through our Cydia repo or directly from here for free! This requires you to either be jailbroken, or have a way to install IPA files (which is not necessarily free)</small>
