### ISSUE TITLE
Add feature to load NDS bios firmware

### ISSUE THREAD

**Issue by slavicweebofficial** [iNDS-Team/iNDS#183]
Adding a NDS bios loader make the emulator function like a real NDS loads the firmware bios you choose would be cool

**Comment by blueingsh** [comment]
if that comes then they should add a option to boot up biod when you open the app

**Comment by Illaminooooo** [comment]
@slavicweebofficial HOW DARE YOU 😡😡😡👎👎👎🟥🟥🟥❌❌❌🤬🤬🤬💥💥💥💥💥CALL ME A STUPID IN UTM?!????!?!?!? YOU KNOW THAT NO ONE CALLS ME THAT BECAUSE ME AND @CLOWNFLY ARE THE KINGS OF THE WORLD AND NO ONE RULES US!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I HOPE YOU ARE 💥💥💥💥🤬❌❌👎🟥👎👎🟥🟥❌💥💥🤬🤬❌🟥🟥👎🟥🟥🟥👎👎👎👎😡BANNED
