### ISSUE TITLE
Dark Mode Issue (bug / mistake?)

### ISSUE THREAD

**Issue by blueingsh** [iNDS-Team/iNDS#186]
**Describe the bug**
When reporting a bug (inside the iNDS app) the text is dark & the background isn’t dark
**To Reproduce**
1. Enable Dark Mode
2. Open iNDS
3. Click the bug icon
4. See bug 

**Expected behavior**

I expected the text to visible and the background to be dark

**Screenshots**

Dark mode
![IMG_3949](https://user-images.githubusercontent.com/55648137/88032394-8088a280-cb03-11ea-9742-25114889defb.png)
Light mode
![IMG_3950](https://user-images.githubusercontent.com/55648137/88032528-b037aa80-cb03-11ea-8776-ba17d0e1b8e9.png)

**Desktop (please complete the following information):**

None
**Smartphone (please complete the following information):**

iOS 13.6

**Additional context**

I don’t have any additional context

**Comment by FrederickGeek8** [comment]
I'll probably remove this function all together when I have a chance. I don't think that bug report feature goes anywhere, unfortunately. It's a relic of the past that was never removed.

**Comment by blueingsh** [comment]
Maybe it should probably redirect you to the Github issues?
