### ISSUE TITLE
Games have missing Artcovers / Update Icon Pack not working

### ISSUE THREAD

**Issue by ResistanceX1** [iNDS-Team/iNDS#190]
**Describe the bug**
I am unable to add Covers to my Games. Tried it with the OpenVGDB Editor but still nothing added even though it is stated as "Success - Icons updated successfully."

**To Reproduce**
Tapping on Update Icons

**Expected behavior**
After adding my Rom to the Correct Game at OpenVGDB Editor the App should add the missing Cover for my Games after updating the Icons

**Smartphone (please complete the following information):**
 - Device: Iphone 11 Pro
 - OS: IOS 13.4.1 Jailbroken with Unc0ver
 - Version 1.10.7 IPA downloaded from Github and installed via Filza

**Additional context**
Hope someone can help me out because my OCD gets triggered

**Comment by blueingsh** [comment]
This has also happened to me, its very annoying

**Comment by m4rkd7** [comment]
Maybe there could be an update to let users manually upload their own cover art?

**Comment by FrederickGeek8** [comment]
Can someone PM me on Gitter? I will try and debug the OpenVGDB Editor. I'm hoping it's a simple issue.

**Comment by FrederickGeek8** [comment]
Unfortunately, it looks like the OpenVGDB Editor is still functioning. Therefore, it's probably an issue on the iOS side (perhaps permissions). Any debugging help would be great as my time is limited.

**Comment by FrederickGeek8** [comment]
This should be fixed in [v1.10.8](https://github.com/iNDS-Team/iNDS/releases/tag/v1.10.8). Try that!

**Comment by secret223** [comment]
> **Describe the bug**
> 
> I am unable to add Covers to my Games. Tried it with the OpenVGDB Editor but still nothing added even though it is stated as "Success - Icons updated successfully."
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> Tapping on Update Icons
> 
> 
> 
> **Expected behavior**
> 
> After adding my Rom to the Correct Game at OpenVGDB Editor the App should add the missing Cover for my Games after updating the Icons
> 
> 
> 
> 
> 
> **Smartphone (please complete the following information):**
> 
>  - Device: Iphone 11 Pro
> 
>  - OS: IOS 13.4.1 Jailbroken with Unc0ver
> 
>  - Version 1.10.7 IPA downloaded from Github and installed via Filza
> 
> 
> 
> **Additional context**
> 
> Hope someone can help me out because my OCD gets triggered
> 
>
