### ISSUE TITLE
INDS black screen on iPhone 8+ iOS 14.2 with multiple ROMs

### ISSUE THREAD

**Issue by dessertg** [iNDS-Team/iNDS#194]
**Describe the bug**
INDS loads ROMs but only a black screen appears. Sound plays in the background, so the games seem to still be running even though both screens are black. 

**Smartphone (please complete the following information):**
 - Device:iPhone 8 plus
 - OS: iOS 14.2
 - Browser: Chrome, Safari
 - iNDS version: 1.10.7 (latest, no cheats, mods, etc.)
 - Jailbreak: checkra1n 0.12.0, INDS installed from Cydia 
- ROMs: Pokémon soul silver, Pokémon white 2; downloaded via chrome; I then selected each ROM and chose open in iNDS 

This is with Pokémon soul silver ROM running, sound in the background:
![E963CF3C-C4F1-4641-92D6-CE4CCF021190](https://user-images.githubusercontent.com/74238552/98656563-cebded80-230e-11eb-9ca9-e5cede3f81a4.png)

Is this potentially an issue with iOS 14.2?
Also, as a side issue: the browser was loading pages improperly in INDS, which is why I downloaded via chrome.

**Comment by rogerrc12** [comment]
Did you manage to fix it? I have the same problem

**Comment by dessertg** [comment]
No sir. The other guy who posted the same issue as #193 says that it’s an issue with the Cydia version, but not the GitHub ipa. 

I run a windows 10 pc, so I’m attempting to setup macOS on a vm. This way I can hopefully use Xcode to install the GitHub INDS.ipa onto my iPhone. Somewhat complicated and I’m kind of a n00b at this, but I couldn’t find another workaround that’s still up and running (Cydia impactor, altstore, etc. aren’t working like they used to) so I’ll let you know how it goes!

**Comment by FrederickGeek8** [comment]
@dessertg These days I would recommend AltStore since it should still work I believe. What problem are you facing? Have you tried opening an issue on their Github?

**Comment by zhepeto** [comment]
For open source apps that you trust them, you can just extract ipa file and copy folder inside payload in the applications. I do this for apps like iNDS and UTM on iOS 14.2.
Don’t forget to respring and uicache after that and please don’t use this way for unknown or close sources apps.

**Comment by FrederickGeek8** [comment]
Can someone who can test `deb` files PM me on [Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)? I can't see what the problem is but I'm hoping it's just a bad build. I don't have a jailbroken device to test on right now.

**Comment by FrederickGeek8** [comment]
I can't reproduce this on my iPhone 6 running iOS 12.5 (look its the only test device I have 😔). Can someone reach out to me on [Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)?

**Comment by FrederickGeek8** [comment]
Try [v1.10.8](https://github.com/iNDS-Team/iNDS/releases/tag/v1.10.8) and see if that fixes the issue.

**Comment by FrederickGeek8** [comment]
I'm not going to reopen the issue but this appears to not be fixed. You can track #193 for updates.

**Comment by woodfairy** [comment]
If you still need jailbroken testers, tell me. I have the issue, tell me how I can help you.
