### ISSUE TITLE
Is it possible to load saves?

### ISSUE THREAD

**Issue by JensOnGH** [iNDS-Team/iNDS#197]
Well I know we have to put saves in the battery folder and change sav. to dsv. but it doesn’t seem to work im trying to run ecdp (the lost mcdonalds game) it doesn’t work on delta and I also prefer iNDS is there any way I can run the save file? because I have to use the save file to get pass the home screen

**Comment by JensOnGH** [comment]
The dsv. And game are the same name also

**Comment by JensOnGH** [comment]
Its also the ipa and im jailbroken and the ipa is the latest version im jailbroken with checkra1n

**Comment by blueingsh** [comment]
The reason it doesn’t work is because the eCDP game comes with a .sav file, iNDS doesn’t support .sav files those are native saves for the DS that you can use with TwiLight Menu++. iNDS only supports .dsv (DeSMUme saves) not native DS saves (I think they can also work with melonDS), You can look up a online converter of .sav to .dsv and import it to iNDS.

**Comment by blueingsh** [comment]
Basically the McDonalds DS game comes with a .sav file and iNDS doesn’t support the .sav file for saves, There is online converts of .sav to .dsv (.dsv is the save files that iNDS supports)

**Comment by JensOnGH** [comment]
When I convert it do I open it in iNDS or put it in the battery folder

**Comment by JensOnGH** [comment]
I used the desume converter and it became a sav dsv do I rename it just to a dsv?

**Comment by JensOnGH** [comment]
What I mean by sav dsv is sav.dsv

**Comment by JensOnGH** [comment]
Ok I used the desmume sav to dsv converted I got my file but its now a sav.dsv is that what I was supposed to do? or do I rename my sav. To dsv. Also how do I import it do I put it into the battery folder? And the sav.dsv says I can load a save but it still doesnt let me press the first option so it doesnt work main questions: how do I import it? Is it supposed to convert to sav.dsv? Do I rename my sav to dsv? Do I put it in the battery folder? Sorry for so many questions

**Comment by JensOnGH** [comment]
Note: First option in the game when I load the save

**Comment by JensOnGH** [comment]
I did not have to convert I had to rename the sav. To dsv. i put the dsv. In the battery folder inds is just not reading the dsv.

**Comment by unlmtd** [comment]
> I did not have to convert I had to rename the sav. To dsv. i put the dsv. In the battery folder inds is just not reading the dsv.

I think you can't just rename the files, because they don't have the same content.

Try the converter and generate a *.dsv from your *.sav. Then you either put the generated file into the Battery folder or you enable Dropbox-Sync beforehand and copy the *.dsv into the iNDS-folder in your Dropbox.

Please let me know if it worked.

As a sidenote: save file import and export should make great features in a future release.

**Comment by JensOnGH** [comment]
Which converter do I use there is allot

**Comment by JensOnGH** [comment]
I cant find a converter I found the only official converter but it makes a sav.dsv and when that is put in the battery folder on inds I can load the save but it doesnt actually work because I cant press the first option in the game and thats what the sav is supposed to do

**Comment by JensOnGH** [comment]
There are some people who are trying to this on ios and delta cant even load the game only the sav so if we figure this out we can probably revive iNDS

**Comment by JensOnGH** [comment]
I think this should be closed theres really no solution

**Comment by blueingsh** [comment]
Use this converter: http://www.save-editor.com/tools/wse_ds_save_converter_for_emulator_desmume_dsv.html

**Comment by JensOnGH** [comment]
Ok i did i got sav.dsv

**Comment by JensOnGH** [comment]
What do I do now

**Comment by blueingsh** [comment]
Open with iNDS or place it in the iNDS folder on DropBox (name the save as same as the rom)

**Comment by blueingsh** [comment]
The iNDS folder is inside the Apps folder in DropBox by the way

**Comment by JensOnGH** [comment]
Ok imma do it can you add me on discord if you dont mind? My name is Jens#1710

**Comment by JensOnGH** [comment]
Uh I put the sav.dsv in the inds folder and it shows up in my battery but its still not working I still cant pick the first option on the game and thats what the save is supposed to do

**Comment by JensOnGH** [comment]
Do i trun off autosave or keep it on?

**Comment by JensOnGH** [comment]
Also I can load the save and launch it normally loading the sav does nothing but makes a dsv

**Comment by JensOnGH** [comment]
I put the dsv. Too but doesnt really change anything

**Comment by blueingsh** [comment]
Did you put the rename the .dsv file to (Rom Name).dsv?
then put it in the iNDS folder or imported to iNDS?

**Comment by blueingsh** [comment]
If you didn't name the save file the same rom name as the McDonalds game then iNDS might be confused and not know which game it belongs to

**Comment by blueingsh** [comment]
Also I can just send you the save file on discord if you want.
My discor is ultwice#5478

**Comment by JensOnGH** [comment]
Ok

**Comment by JensOnGH** [comment]
I added you

**Comment by JensOnGH** [comment]
Also they are the same name and can you send me the dsv.?

**Comment by blueingsh** [comment]
Sure ill upload on drive and send you the link

**Comment by FrederickGeek8** [comment]
There is a solution! Or, rather, it at least works for me.

There is a subtle difference between DSV and SAV files. A kind user on archive.org was able to convert to a DSV file (that works for me): https://mega.nz/folder/I1B2AToL#ua7qseSEqs6I2JICw5-IuQ

For those weary of download suspicious stuff, I ran a hex diff on the SAV and DSV file and truly the only difference is that difference between the two file formats.
<img width="882" alt="Screen Shot 2021-01-05 at 7 41 17 PM" src="https://user-images.githubusercontent.com/774597/103642378-fdaeb380-4f8d-11eb-94b3-ae0565b73439.png">
