### ISSUE TITLE
Cant download aby to

### ISSUE THREAD

**Issue by sutk0wsky** [iNDS-Team/iNDS#200]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blueingsh** [comment]
what?

**Comment by FrederickGeek8** [comment]
Closing this as spam since the template wasn't filled out, the author didn't respond for clarification, and the title doesn't make sense
