### ISSUE TITLE
Remove button

### ISSUE THREAD

**Issue by overlander86** [iNDS-Team/iNDS#205]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FrederickGeek8** [comment]
Hey! Can you provide more details about the feature you're requesting? I'm not sure what you mean by "Remove button".

**Comment by overlander86** [comment]
I want to remove one game not a bunch of games

**Comment by FrederickGeek8** [comment]
Have you tried swiping to the left on the game you want to remove? There should be a remove button that appears.
