### ISSUE TITLE
Bug soulsilver iNDS ios 14.2

### ISSUE THREAD

**Issue by thijssieZ** [iNDS-Team/iNDS#208]
**Describe the bug**
Models not working, black screen appearing

**To Reproduce**
1. Open Pokemon Soulsilver in iNDS
2. go through the basic progress of creating a character
3. walk down the stairs to the npc mom and talk to her until you can walk out of the house
4. walk out of the house and you see the error

**Expected behavior**
models will glitch and if you walk into a building again, you will see a blackscreen

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iphone 7
 - OS: IOS 14.2
 - Browser Safari

**Additional context**
none

**Comment by unlmtd** [comment]
I think the problems with Pokémon SoulSilver and HeartGold are related to DeSmuME.

If you want, you can try the same ROM on the Windows version of DeSmuME. If the problem remains, it's not about iNDS and we can't do anything about it currently.

Some users report different behaviors with different ROMs. You can try that as well.

In the future, the integration of a second core is planned and it'a possible that the new core fixes the problem.

Please report back if any of my suggestions helped.

**Comment by FrederickGeek8** [comment]
I actually just tested this on DeSMuME v0.9.11 on macOS and it seems to work fine. On iNDS on the other hand, I have the described issue. **BUT** changing the Depth Comparison Threshold in the Setting to 300-400 fixes the bug (I'm not sure on what value is needed to fix the bug)

Let me know if you still run into issues.
