### ISSUE TITLE
No thumbnails (iPhone 11 Pro Max) (iOS 14.3) Update Icons not working

### ISSUE THREAD

**Issue by NerdyWanKenobi** [iNDS-Team/iNDS#211]
**Describe the bug**
I tried using Update Icons and it said it was successful but it didn't add any icons. The games I have are the Gen IV and V Pokémon Games, NSMB, Mario Kart DS, and various ROM hacks.

**To Reproduce**
1. Go to 'Settings'
2. Scroll down to 'icons'
3. Choose 'Update Icons'

**Expected behavior**
It should add thumbnails to your games.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 11.1 Big Sur
 - Browser: Safari
 - Version 14

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.3
 - Browser: Safari
 - Version 14

**Additional context**
Plz help

**Comment by FrederickGeek8** [comment]
This issue should be fixed in [v1.10.8](https://github.com/iNDS-Team/iNDS/releases/tag/v1.10.8). Try updating to that!
