### ISSUE TITLE
Crash When Opened

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [iNDS-Team/iNDS#216]
I just signed the IPA with 3uTools and now when I open it crashes, I have everything synced to Dropbox so I don't loose everything, but how can I fix.
**To Reproduce**
1. I used 3uTools to Sign IPA
2. I trusted and verified on my iPhone XR IOS 14.0.2 (Not Jailbroken)
3. Open the iNDS app
4. It crashes

**Expected behavior**
I want to open, sign into dropbox and play.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Not sure

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: IOS 14.0.2
 - Browser: Safari
 - Version: Trying to install Latest version of iNDS

**Comment by Pixelplayz2215YT** [comment]
I was able to use it on TuTuApp, then once the license got revoked I tried to re-download it, but it didn't work on TuTuApp so I used 3uTools, and still won't work.

**Comment by FrederickGeek8** [comment]
I'm not familiar with 3uTools but it sounds like a problem with their application signing iNDS properly. Maybe try AltStore? I haven't used it myself, but it seems to be a mainstream solution these days.

**Comment by Pixelplayz2215YT** [comment]
I'll tell you if AltStore worked!

**Comment by Pixelplayz2215YT** [comment]
> I'm not familiar with 3uTools but it sounds like a problem with their application signing iNDS properly. Maybe try AltStore? I haven't used it myself, but it seems to be a mainstream solution these days.

The AltServer won't download onto my phone from my PC, any other IPA signer I can use?

**Comment by Pixelplayz2215YT** [comment]
Hey, just making sure you got my last comment, AltServer doesn't work, any other ipa signer?

**Comment by Pixelplayz2215YT** [comment]
You can close this problem, I used Sideloadly and it works
