### ISSUE TITLE
Syncing With Dropbox

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [iNDS-Team/iNDS#220]
**Describe the bug**
After Syncing with drop box once, everything was in the iNDS app, now after re-installing it and Signing in with dropbox to re-sync everything, none of my games show up.

**To Reproduce**
1. Sync with Drop box
2. The certificate get's Revoked
3. Re-Download iNDS
4. Sign into Dropbox
5. Nothing is in ROMs list
6. Restart iNDS still nothing

**Expected behavior**
I want my games with Save Data

**Screenshots**
![IMG_5654](https://user-images.githubusercontent.com/79018578/109556260-95b7ad80-7aa4-11eb-9da7-4c0d2911d2c9.PNG)
![IMG_5655](https://user-images.githubusercontent.com/79018578/109556297-a23c0600-7aa4-11eb-9d5e-4c9ca31165c7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Not sure

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 14.3
 - Browser: Safari
 - Version: If referring to iNDS version Latest 1.110.7

**Comment by Pixelplayz2215YT** [comment]
Or does it only sync save data and not the games?

**Comment by FrederickGeek8** [comment]
Correct. It only syncs save data and not games.

**Comment by Pixelplayz2215YT** [comment]
> Correct. It only syncs save data and not games. 

Thank you, is thier a discord server I can join?

**Comment by FrederickGeek8** [comment]
Not Discord, but [Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). It's like Discord but for Github accounts. If you have any quick questions you can ask there, or DM me for hands-on help.
