### ISSUE TITLE
Black screen on every rom 

### ISSUE THREAD

**Issue by taroute** [iNDS-Team/iNDS#223]
Black screen on EVERY rom.

i heard the sound but can’t see anything. The game run at 60 FPS

I’m on IPhone X
IOS 14.4
Jailbroken with latest version of checkra1n 
I’m using INDS 1.10.8
Downloaded on official repo. 

i try it on Pokémon hearthgold and black and animal crossing. 
The game work well on nds4ios but INDS is a way better !

I view some people having the same issue in Reddit but no one got a solution

**Comment by NerdByFate** [comment]
This appears to be the same as #193. Someone reported that rebuilding the .deb from the .ipa worked for them, so you might try that.

**Comment by taroute** [comment]
Finally I manage to make it work by download the ipa from GitHub then install it with Filza.


.deb file on GitHub don’t work and Cydia too
