### ISSUE TITLE
Microphone Issues

### ISSUE THREAD

**Issue by FrederickGeek8** [iNDS-Team/iNDS#27]
**Describe the bug**
Microphone does not appear to work, and from what I can see, seems to have not worked for a while.

**To Reproduce**
1. Obtain "The Legend of Zelda: Phantom Hourglass"
   2. Create a new save file
   3. Click "Start" -> "Options" -> "Mic Test"
   4. Mic doesn't work
1. Obtain "Nintendogs"
   2. Adopt a pet
   3. Pet said pet until you are asked to give it a name verbally
   4. Mic doesn't work

**Expected behavior**
Microphone should respond to verbal input, however, it does not.

**Version Information:**
 - OS: iOS 11.4
 - Version 1.8.1

**Additional context**
I suspect that this is an issue of the EZAudio library (used for the microphone) conflicting with the implementation used to play output audio.

**Comment by genkino** [comment]
* This issue occurs because you do not have microphone rights. I made a change from the previous repository base and left a link to help. 
[https://github.com/genkino/iNDS/commit/f88f51ab7e28d34642f111097bdd47849d93413e](url)

**Comment by FrederickGeek8** [comment]
I'll check that out. In my local fork I made changes that should have allowed for microphone permissions but that didn't help the issue. If you say your changes work, then that's great!

**Comment by FrederickGeek8** [comment]
@genkino It appears to face some of the issues I was having with some of the initial modifications I made trying to fix this issue. The changes seem to disable the audio output, and I'm unable to test whether there the audio input has changed (Zelda still shows maxed out bars and Nintendogs would play back what I said, however, I'm unable to hear it).

Did those modifications work back in March when you made them? On what iOS version, etc?

**Comment by genkino** [comment]
When Zelda was turned on, it worked normally to turn off the candle. I'll check again with the new source now. The environment I tested was iOS 11. :)

**Comment by kmilner** [comment]
I think I have addressed this in #69. The issue was both in asking for microphone permission as well as the actual microphone sampling, which needed to be shifted down to 7 bit samples.

On my device (an iPad Pro) the unadjusted 7 bit samples seemed to be about the correct volume level without needing to do any dampening. I tested that in both Nintendogs and in Pokemon Black's built-in mic test.

**Comment by FrederickGeek8** [comment]
Fixed in #69. Not sure why this is still open.
