### ISSUE TITLE
8bitdo controller icade controller

### ISSUE THREAD

**Issue by ha5696** [iNDS-Team/iNDS#29]
Please correspond to Bluetooth controller, 8bitdo controller, icade.

What I use is fc30pro.

**Comment by FrederickGeek8** [comment]
If you're asking for support for 8bitdo or iCade controllers, there should already be support (via [WilliamCobb/iNDS#228](https://github.com/WilliamLCobb/iNDS/pull/228) and [WilliamCobb/iNDS#36](https://github.com/WilliamLCobb/iNDS/pull/36)).
