### ISSUE TITLE
Cydia Repo

### ISSUE THREAD

**Issue by FrederickGeek8** [iNDS-Team/iNDS#3]
In the future, depending on the needs of the users, we might elect to have a Cydia repository. As I do not have a jailbroken device, those who wish to be a part of testing the new repository may express their interest here.

**Comment by jsxn** [comment]
Will JIT work on non jailbroken devices? I’m not sure about that if not I have a 11.1.2 iPhone X if jit needs jailbreak :)

**Comment by jsxn** [comment]
Once jit support is available (if isn’t already) then that will be one of the main reasons also I have a 11.1.2 iPhone X but would need steps to how to set up cydia repo

**Comment by FrederickGeek8** [comment]
A (beta-ish) repository is now up, along with an updated website! You can add the new repository to Cydia as `inds.nerd.net`. Currently, only version 1.8.1 (the most recent as of July 4th, 2018) has been uploaded.
