### ISSUE TITLE
No Sound when changing games sometimes 

### ISSUE THREAD

**Issue by Wh0ba** [iNDS-Team/iNDS#33]
The sound gets kind of muted when switching to another game 
I'm saying kind of because in the game there is no sound but if I open the menu then close it 
I hear the game sound for a second then it stops

**Comment by FrederickGeek8** [comment]
I'm having trouble reproducing this issue given the current information on the bug. Could you perhaps fill out the bug template or give some more information so I could perhaps reproduce the bug?

**Comment by DatNightcat** [comment]
[https://www.youtube.com/watch?v=pcPcF2WzuyU](Here's my video showcasing it. Synchronous Audio is off.)
The video in a nutshell, and if it ever becomes unavailable:
1. The game loads with no audio issues.
2. Another game gets loaded, but with no audio.
3. I pause and unpause. Sound works for about half a second before cutting out again.
4. I load from a savestate, temporarily fixing the issue.
5. I load another game, showing that the savestate fix is temporary.
6. I force close the app and load a game, showing that the issue fixes itself.

**Comment by FrederickGeek8** [comment]
Okay I was able to reproduce with the instructions from @DatNightcat

**Comment by FrederickGeek8** [comment]
Update on this: It appears to be a problem with `SPU_Pause`. Commenting out the pausing in `emu.cpp` fixes the issue. I'm looking into a better fix right now.
