### ISSUE TITLE
Games Not Throttling

### ISSUE THREAD

**Issue by FrederickGeek8** [iNDS-Team/iNDS#36]
**Describe the bug**
When running on capable hardware, games do not appear to throttle down to normal (1x) speed, and instead play as fast as they can. 

**To Reproduce**
1. Download a ROM on capable hardware (e.g. A1701 iPad Pro) 
2. Play game
3. Observe?

**Expected behavior**
The game should run at a normal speed

**Smartphone (please complete the following information):**
 - Device: iPad Pro 10.5 A1701
 - OS: iOS 11.3.1
 - Version 1.8.2

**Additional context**
Installed via Cydia. I observed this in Pokémon White 2 as well as other ROMs. You can compared against no commentary playthroughs if you don’t believe that the emulator is not throttling.

**Comment by FrederickGeek8** [comment]
It is clear to me now that this is not isolated to Cydia releases, but to the general application (at least the Release build configuration). Its hard to tell if this only affects the Release builds or not since Debug builds are supposed to be slower in nature, and thus appear to be running at native speed.

**Comment by Canatee** [comment]
Same issue on 1.8.1 from buildstore, ios 11.4 ipad pro 10.5

**Comment by FrederickGeek8** [comment]
We should set the `preferredFramesPerSecond` to 60 in `iNDSEmulatorViewController.mm`. i.e. add
```objective-c
coreLink.preferredFramesPerSecond = 60;
```
after https://github.com/iNDS-Team/iNDS/blob/18880a702c7d846aaed8b65cbce526cd06df974d/iNDS/iNDSEmulatorViewController.mm#L270
