### ISSUE TITLE
Show Nintendogs game name in ROMs list

### ISSUE THREAD

**Issue by DatNightcat** [iNDS-Team/iNDS#38]
**Is your feature request related to a problem? Please describe.**
I have a ton of versions of Nintendogs for the sake of having a ton of dogs. However, due to the fact that the icons don't appear right now, it means that I have to keep looking around until I find the game I'm looking for.

**Describe the solution you'd like**
I'd like the game's full name to show up next to the word "Nintendogs" because compared to the DS, we have enough room to show it.

**Describe alternatives you've considered**
One alternative is creating a savestate with the game's full name or the names of the dogs in that save file.

**Additional context**
![img_3851](https://user-images.githubusercontent.com/26909213/43121387-45a63f58-8f26-11e8-9fc5-772d3ea8d704.jpg)
All of these say "Nintendogs" which isn't very helpful.

**Comment by FrederickGeek8** [comment]
Hmm, I one possibility is to maybe add a feature where you could rename games. Would that be something that would help you?

**Comment by FrederickGeek8** [comment]
I'm working on said functionality over at [FrederickGeek8/iNDS/tree/custom-titles](https://github.com/FrederickGeek8/iNDS/tree/custom-titles). Everything is working, however, it appears you can only edit the title once per app launch. I'll work on it some more tomorrow.
