### ISSUE TITLE
The built-in web browser does not size correctly on iPad.

### ISSUE THREAD

**Issue by noah978** [iNDS-Team/iNDS#42]
**Describe the bug**
The built-in web browser does not render properly on 9.7” iPad Pro.

**To Reproduce**
1. Simply open the built in web browser on an iPad.

**Expected behavior**
The actual size for the web browser will appear iPhone sized in the top left corner of the iPad screen.

**Screenshots**
![904e79b9-05de-40ea-ba62-13fd356d4fa8](https://user-images.githubusercontent.com/26331126/43531121-bf116a3a-9574-11e8-8056-7768cbedc565.png)

**Smartphone**
 - Device: 9.7” iPad Pro
 - OS: iOS 11.4.1
- Version: 1.8.1

**Comment by FrederickGeek8** [comment]
I can reproduce in landscape mode on my iPhone X. I suspect it’s an auto layout issue. Should be an easyish fix.

**Comment by FrederickGeek8** [comment]
I added a fix for this to #41. You can check out that pull request if you want to make sure its fixed.
