### ISSUE TITLE
Desmume version

### ISSUE THREAD

**Issue by ElementalEnd** [iNDS-Team/iNDS#43]
I know updating to 0.9.11 is on the list, but when is it estimated to happen? I really wanna play ace attorney, but the examinations don’t work 0.9.10.

Also, just a note in case you need it, I got the emulator from iEmulators.

EDIT: Okay, I’ve realized that the iEmulators version is still at version 1.3.5, so does that one just never get updated? Does that mean I have to get it a different way to keep it updated?

**Comment by FrederickGeek8** [comment]
Updating to version 0.9.11, unfortunately, does not completely fix the examination stage (in my experience). 

On the topic on iEmulators, I was under the impression that the service was in some way affiliated with [BuildStore](https://builds.io). I will reach out to them and make sure the emulator is updated. You should be able to verify what version you are running in the Settings menu.

**Comment by FrederickGeek8** [comment]
It might be the description thats out of date. You can check the version of the app at the bottom of "Emulator Settings":
<img src="https://user-images.githubusercontent.com/774597/43617754-613bf622-9692-11e8-90f6-605330cf2c5b.jpg" height="400" />

**Comment by ElementalEnd** [comment]
Yeah I updated my comment. The description was outdated, the actual app is on 1.8.1
