### ISSUE TITLE
iNDS crash at startup with pokemon games with 1.9 version

### ISSUE THREAD

**Issue by Raptor039** [iNDS-Team/iNDS#44]
**Describe the bug**
Since 1.9 version, iNDS crash at startup when a pokemon nds file is present on internal memory of my iPad. For information, all is working fine with 1.8.3 version of iNDS

**To Reproduce**
1. Go to iTunes and drag and drop a pokemon nds file
2. Launch iNDS after the rom transfer is complete
3. iNDS crash after a few seconds

**Expected behavior**
When nds file of any pokemon games are present, iNDS should launch properly

**Smartphone (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS 11.4.1

For information, it works with english localized rom but not whith french rom, wich is type of rom I'm using.

**Comment by FrederickGeek8** [comment]
Hey! I would suspect it would have to do with the localization of your ROMs. Could you contact me [on Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) so I can help out further?

**Comment by FrederickGeek8** [comment]
That commit should solve the problem. Tell me if it does not (or if you need an IPA or deb file to test with).
