### ISSUE TITLE
Generating IPA files?

### ISSUE THREAD

**Issue by EdwardElric64** [iNDS-Team/iNDS#47]
Hi guys, I have a non jailbroke 6+ running iOS 11.3, and I use Cydia impactor on the daily basically whenever an emulator needs an update, But recently I read that there was a fix for the microphone and I have no idea how to compile an ipa on Windows. I have absolutely no other apple product other than my iPad Air and this phone.
EDIT: I’ve seen something about using a VM to get Xcode, but the last time I tried to download it through the savana OS I always got a failed download error

**Comment by FrederickGeek8** [comment]
To my knowledge, the microphone issues (tracked in #27) have not been fixed.

**Comment by EdwardElric64** [comment]
Drat, is there an ETA on when this could be fixed? (Btw it’s awesome that you guys picked up iNDS development)

**Comment by EdwardElric64** [comment]
So uh... After cloning it in xcode I'm hit with a mess of errors https://imgur.com/a/04fpQIx

**Comment by syto203** [comment]
Change the name and bundle identifier to anything other than what’s written

**Comment by EdwardElric64** [comment]
Still same problem. When I click the play button I get a bundle error

**Comment by FrederickGeek8** [comment]
@EdwardElric64 go into Terminal, run `cd <iNDS directory>`, then `./genipa` to build an unsigned IPA

**Comment by FrederickGeek8** [comment]
Closing this since I believe the issue has been resolved.
