### ISSUE TITLE
Wario Ware D.I.Y. Doesn’t work.

### ISSUE THREAD

**Issue by PandaPJYuri** [iNDS-Team/iNDS#49]
I pretty sure you already know of this sort of problem, but can we expect it to get fixed?

**Comment by FrederickGeek8** [comment]
Based on your issue, I don't know what problem you are referring to. It is very useful to [fill out the bull report template when posting an issue.](https://github.com/iNDS-Team/iNDS/issues/new?template=Bug_report.md) I would encourage you to still fill it out.

**Comment by PandaPJYuri** [comment]
iOS 12 (also didn’t work on iOS 11.4)
iPhone SE
Ver. 1.5.3
iEmulators

Try to get Wario Ware D.I.Y. Rom (any will do) open. Get black screen.

**Comment by FrederickGeek8** [comment]
This appears to be a known issue with older versions of DeSmuMe. Doing a quick Google Search, there appear to be some workarounds for these versions that involve modifying the ROM file. Of course, you could wait until the core DeSmuMe is updated to 0.9.11 (which could happen soon depending on whether I can duplicate some changes I made in the past on newer versions of iNDS).

**Comment by PandaPJYuri** [comment]
The workarounds don’t work for me so i’ll Wait.
