### ISSUE TITLE
So this project is for the emulator of machine codes on NDS?

### ISSUE THREAD

**Issue by NHibiki** [iNDS-Team/iNDS#5]
**Features**
Is it going to be parsing any machine codes from NDS binary file and then turning it into swift (or c) codes? Or just simulate the logic appears in NDS?

**Comment by FrederickGeek8** [comment]
If I understand your question correctly, this should more closely simulate the logic. Although there is some translation / JIT'ing involved, this is not aimed to creating any sort of output binary. 

The project is built around the [DeSmuME project, which you can check out here.](https://desmume.org/)
