### ISSUE TITLE
Touch Responsiveness(Sometimes Not Working)

### ISSUE THREAD

**Issue by SpaghettiSouls94** [iNDS-Team/iNDS#50]
I don’t know if im pressing the buttons incorrectly or if the touch responsiveness is not... Responding. Besides that, this is most consistent NDSI Emulator i’ve seen on ios

Edit: I don’t know if its a bug but, on my iPhone 7 touching the D-Pad Sometimes results in no output by the D-Pad which causes gameplay to become harder and me tapping my D-Pad Aggressively. And I absolutely did that on my 6s and broke it. Sorry for not putting these details in earlier 

*********************************************
- Device: iPhone 7
- iOS: 11.4.1
- Browser: Safari
- Version: 1.8.1
*********************************************

**Comment by FrederickGeek8** [comment]
What device and emulator version are you using? iPhone X? In the future, we have an [Issue Template](https://github.com/iNDS-Team/iNDS/issues/new?template=Bug_report.md) when creating a new issue.
