### ISSUE TITLE
Touch Responsiveness (Partially Working)

### ISSUE THREAD

**Issue by SpaghettiSouls94** [iNDS-Team/iNDS#51]
I don’t know if im pressing the buttons incorrectly or if the touch responsiveness is not... Responding. Besides that, this is most consistent NDSI Emulator i’ve seen on ios

I don’t know if its a bug but, on my Device, touching the D-Pad Sometimes results in no output by the D-Pad which causes gameplay to become harder and me tapping my D-Pad Aggressively. And I absolutely did that on my 6s and broke it.

*********************************************
- Device: iPhone 7
- iOS: 11.4.1
- Browser: Safari
- Version: 1.8.1
*********************************************
Whilist Continuously Playing, I also Discovered that the D-Pad is going up whlist I touch Left D-Pad/Right D-Pad. But also the B button sometimes is also never getting registered. I Also took a screen test and it seems that my screen is working perfectly. Is there an option to make your buttons bigger?
*********************************************
Fix By FrederickGeek8:
There is an option to change the screen layout, which includes resizing buttons. While in a ROM, you can go to Settings -> Layout Settings -> Edit Profile Layout to begin editing.

**Comment by FrederickGeek8** [comment]
Yes. There is an option to change the screen layout, which includes resizing buttons. While in a ROM, you can go to Settings -> Layout Settings -> Edit Profile Layout to begin editing.

To contributors: This (usage) might be a good wiki topic  😉

**Comment by SpaghettiSouls94** [comment]
Thanks this helped so much. I am about to beat kirby super star ultra and my buttons were being annoying.
