### ISSUE TITLE
Emulator fails to open .nds file from ZipApp or safari 

### ISSUE THREAD

**Issue by AnonymousDeveloper13** [iNDS-Team/iNDS#53]
Usually it will end up with something like this Unable to open file: Unknown Error (1, 0, file:///private/var/mobile/Containers/Data/Application/EA781821-0594-4C2F-A7C7-B33F7E17452C/Documents/Inbox/Pokemon%20Platinum-1.nds)
I’m on version 1.8.3

**Comment by FrederickGeek8** [comment]
Were you able to solve this?

**Comment by AnonymousDeveloper13** [comment]
Yes sorry for late reply
