### ISSUE TITLE
Pokémon soul silver some audio isn’t correct 

### ISSUE THREAD

**Issue by kanodls** [iNDS-Team/iNDS#54]
Audio not sounding right for some Audio cues (Pokémon sprites jumping in world, Pokémon faint animation sound and xp bar progression sound) video example(https://youtu.be/yLi0agnyL8M)
iPhone X in jail broken
11.4.1

**Comment by FrederickGeek8** [comment]
Hmm... I think I hear the problem, though I'm not completely sure as I have not played the game myself. I'll assume you know what you're talking about.

What version of iNDS are you running? Have you tried enabling Synchronous Audio in settings to see if that improves the audio?

**Comment by kanodls** [comment]
Synchronous Audio is buggy for me (staticy and choppy) so I don’t use it. I am using version 1.9.1

**Comment by Dry05** [comment]
Try 1.9.2b1 it runs perfect on there

**Comment by FrederickGeek8** [comment]
Closing this issue as it is assumed solved in 1.10.0.

**Comment by VrtlBrown** [comment]
@kanodls which ROM of Soul Silver are you using? I couldn't find one that worked with iNDS, each one I used my character sprite would turn into a black square after a few minutes and the whole screen would turn black eventually.

**Comment by Dry05** [comment]
Happened to me too on heart gold. It seems to always happen on any rom version eventually. However I found a fix, https://forum.romulation.net/threads/pokemon-hg-ss-original-ap-patched-usa-eur.58215/ it’s a graphical fix. Try the patched rom or just enter the cheat code when you launch the rom. I played for over 2 hours without problems

**Comment by VrtlBrown** [comment]
@Dry05 thanks very much, I moved on to White 2 after I couldn't get it to work, but SS was supposed to be one of the best. Thanks again!
