### ISSUE TITLE
Buildstore version outdated?

### ISSUE THREAD

**Issue by MikePresJr918** [iNDS-Team/iNDS#55]
I'm noticing were up to 1.9.1 here but buildstore.io still has 1.8.3 listed from June. Any chance of an update for buildstore soon?

**Comment by MikePresJr918** [comment]
I just reinstalled from builds.io, settings still lists 1.8.3. You got 1.9 from buildstore?

**Comment by MikePresJr918** [comment]
I wasn't aware I could do that myself, that is very helpful information :) do I just pop them an email and let them know a new build is out?

**Comment by FrederickGeek8** [comment]
I've already sent them a Twitter DM, but normally I just say that a new release is out and send them a link to the [Releases page: https://github.com/iNDS-Team/iNDS](https://github.com/iNDS-Team/iNDS)

**Comment by MikePresJr918** [comment]
Update:

I’ve reached out to them via twitter again, it looks like iEmulators have updated to 1.9.1 but unfortunately IEmulators tend to inject add software into the programs, buildstore still confirmed 1.8.3. Will update again once builds.io updates iNDS on the store or DMs me back.

**Comment by FrederickGeek8** [comment]
I've reached out to Buildstore to update iNDS to 1.10.0, so I'm closing this issue.
