### ISSUE TITLE
Not sure if this is the correct place to report this

### ISSUE THREAD

**Issue by CourtneyBrz** [iNDS-Team/iNDS#59]
I was playing Pokemon diamond through iNDS for the last week and I tried to open the app today and it popped up saying the app needs to be verified which I verified a week ago. I go to try and verify the app again & it doesn't go through and will no longer let me access the app or game. I went to Iemulators and it says the app has been updated and try to install again but it also not working. I looked up videos on how to access my saved progress and I connected my phone to iTunes and when I go to click on the iNDS app I see that my saved progress doesn't come up but a folder for battery that I assume has my saved progress comes up but it won't allow me to transfer that folder to my desktop or to my files. Why is that? Am I able to access my saved progress or am I doing something wrong because I would like to be able to figure this out. Another thing what is the best place to keep my saved progress so this will not happen again? Thanks.

**Comment by syto203** [comment]
The app verification is from iemulators nit from iNDS. To get your saves you need to get that battery folder, you can do so using iTunes 12.6.5 which still supports Apps or use a 3rd party tool like iMazing or ifunbox to get your saves. If however you deleted the App or tried to install a new one over it you might’ve deleted them.
If you backed up your phone they will backup as well so use a backup viewer/extractor to get them, and if you used Dropbox sync they’ll be synced as well (Highly encouraged to avoid data loss).
Regarding the verification error you have multiple options:
1- jailbreak your device
2- sideload the App yourself using XCode or impactor (only for 7-days and needs to be sideloaded again)
3- use a paid signing service to avoid interruptions although these too can get revoked by Apple.

**Comment by FrederickGeek8** [comment]
@syto203 is right as this is not an iNDS issue, and I would likely try their solution to get the files off of it. If I were you, I would contact iEmulators and see if they can help you. I will close this issue for now but feel free to update me on your endeavors.
