### ISSUE TITLE
Bottom buttons don't register

### ISSUE THREAD

**Issue by circa-one** [iNDS-Team/iNDS#62]
**Describe the bug**
The virtual buttons that touch the bottom of the screen to not register on first tap. It takes multiple taps to get them to register. Buttons affected: Down arrow, Start, Select, and B buttons.

**To Reproduce**
Open any rom, press any of the bottom buttons mentioned above.

**Expected behavior**
Buttons to register on first tap.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 12.0.1
 - Browser: Safari
 - Version:

**Additional context**
Downloaded from the BuildStore. They recently uploaded the recent version of iNDS I believe. I didn't have this issue before redownloading the app.

**Comment by FrederickGeek8** [comment]
I think this might be related to #14. I thought this was an issue specific to iPhone X's, but I'm not really sure if Apple made further restrictions for other devices. It is out of the "safe area" of the screen that Apple defines in their documentation and Xcode.

**Comment by circa-one** [comment]
It wasn’t an issue before the last update that was uploaded to the BuildStore. Before that, it functioned correctly. Now the app basically unusable until the issue is resolved.

**Comment by FrederickGeek8** [comment]
@circa-one could you be more specific about the versions that you are talking about? You can always check the version at the bottom of the settings menu in iNDS.

**Comment by circa-one** [comment]
Version 1.9.1 is what mine says.

**Comment by nanogram** [comment]
Just tested it on v1.10.2 on my iphone 8 and all the button inputs work fine, although i just noticed the D-pad doesn't vibrate lol.

**Comment by FrederickGeek8** [comment]
I also could not reproduce this (on an iPhone 6)

**Comment by circa-one** [comment]
So it must be an issue with plus sized devices only then?

**Comment by Silfalion** [comment]
Still have the same problem
