### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by nanogram** [iNDS-Team/iNDS#68]
Plz consider having an update option, either by having a notification appear when an update is ready(like the suggestion to follow on twitter) or have an update button in the menu. It would be helpful for those who use Cydia Impactor(like me :) ).

**Comment by FrederickGeek8** [comment]
Good idea! I will definitely look into adding this feature.

**Comment by FrederickGeek8** [comment]
A check for update feature has been added to the settings menu!
