### ISSUE TITLE
Huge Battery Drain

### ISSUE THREAD

**Issue by nanogram** [iNDS-Team/iNDS#70]
iOS device: iPhone 8
iOS version: 1.11.3
Jailbreak status: Not Jailbroken
Download location: Github
Current iNDS Version: 1.10.1

This is a great app, but unfortunately, drains the battery very fast.
I tested this on my iPhone by clearing out all background apps, turning on low power mode, and playing iNDS (pokemon white 2). I played for two hours before checking my battery percentage, and it had dropped over 50%!!! Not sure why it drains battery that fast, especially since the phone was on low power mode(which gave it an average core clock of 90-100, according to the fps dev tool).

**Comment by FrederickGeek8** [comment]
I have to agree with @noah978, unfortunately. There may be some tweaks I can make to improve battery life, but it will still drain your battery very fast since it is an emulator.
