### ISSUE TITLE
Reset Content

### ISSUE THREAD

**Issue by kevincool510** [iNDS-Team/iNDS#74]
I accidently reset ( erase all content. But my storage didn't decrease so it's mean that maybe the game is still somewhere in my iphone, it's there a way to recover the game or save files ? please help me i'm on version 1.9.1 ( sorry for the bad english )

**Comment by syto203** [comment]
First of all, this isn’t an issue. 

However, If you backed it up on dropbox or made a backup of your device you might get it back if you didn’t then sorry you can’t.

**Comment by nanogram** [comment]
Possible Enhancement: Maybe have another button pop up after u hit reset, saying “Are you absolutely sure you want to reset?” w/ yes/no options
Or maybe do away with the reset button, bc the user could just delete and redownload the app.

**Comment by FrederickGeek8** [comment]
Sorry about that! I would check Dropbox to see if you can recover your save files. We will definitely put a verification on the button though. The button was originally for debugging purposes, I never thought it would accidentally be pressed.
