### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by syto203** [iNDS-Team/iNDS#8]
i cloned this fork and tried building, at first i got the pod file not found error so i installed cocoa pods, but when building i get the error "ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h file not found".

![screen shot 2018-05-21 at 2 33 29 pm](https://user-images.githubusercontent.com/26351342/40309213-fb77aefc-5d08-11e8-9580-52318d732d09.png)

**Comment by FrederickGeek8** [comment]
Oh no! I forgot to include some installation instructions for those not familar with Cocoapods. I will update the Wiki soon, however, it sounds like you have already run `sudo gem install Cocoapods` to install Cocoapods. To install the Pods for this project however, in Terminal, you should `cd` to the iNDS git directory and run `pod install`, which should install the required dependencies.

**Comment by Hollr2099** [comment]
It might be an error on my end but I have never had this problem before building any apps

**Comment by FrederickGeek8** [comment]
@Hollr2099 [Join our Gitter chat room](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) where I can give more hands-on support for the issues.

**Comment by FrederickGeek8** [comment]
I updated the [wiki page for building for Jailed devices](https://github.com/iNDS-Team/iNDS/wiki/Building-iNDS-for-Jailed-iDevices) to be updated for the Cocoapods changes. I do however suggest that you join the Gitter chatroom if you are having any troubles and want some instant, hands-on support from me.

**Comment by FrederickGeek8** [comment]
@syto203 , @Hollr2099 was able to resolve their issue. Were you able to resolve yours? I see that you have opened another issue that makes it seem as though this one should be closed...

**Comment by jsxn** [comment]
I have this same error and I've installed the pods and tried to do it for iNDS but gives me the thing that op posted
