### ISSUE TITLE
[Feature Request] Add support for URL Schemes

### ISSUE THREAD

**Issue by noah978** [iNDS-Team/iNDS#81]
I recently created a collection of Siri shortcuts (originally workflow) that allow a user to quickly create a url scheme that will automatically open a specific game in gba4ios. All they need to do is type in what the ROM is named, the shortcuts will convert it into a URL scheme, then select an image, and a direct link to the game will be added as a home screen icon.

It would be a great (hopefully simple) feature to add to iNDS to make it easier to access games for users. The links to my shortcuts are below.

https://www.icloud.com/shortcuts/69d6beee9bfe4ac6b67fa9fc653b4021

https://www.icloud.com/shortcuts/94b58a89fb5e4df59955dfd87a477c12

**Comment by FrederickGeek8** [comment]
Are you using Cydia Impactor or Cydia? If so, could you message me on [Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)? I have created a build with what I believe to be shortcut support, but I would like someone to test it.
