### ISSUE TITLE
Load Game

### ISSUE THREAD

**Issue by KnittedKnife64OwO** [iNDS-Team/iNDS#84]
hey so...you have a save feature, but no load?? i mean the GBA emu. had both and then some but, you know im just not sure i can use this emulator without a load state.

**Comment by FrederickGeek8** [comment]
When you create a save state, it is located and can be loaded from Game / Current ROM menu, e.g., when you select what game you want to play, you are presented with your save states. If you are currently playing a game, you can select the save state in the "Current ROM" menu. Does that answer your question?
