### ISSUE TITLE
Map Start Button to Pause on MFi Controller

### ISSUE THREAD

**Issue by ILikePlayingGames** [iNDS-Team/iNDS#87]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to pause games using my controller.

**Describe the solution you'd like**
Please map the DS start button to the pause button on MFi controllers.

**Describe alternatives you've considered**
Using the virtual start button on the touch screen

**Additional context**

**Comment by FrederickGeek8** [comment]
I do not have an MFi controller to confirm, but [according to Apple documentation](https://developer.apple.com/documentation/gamecontroller/gcextendedgamepad?language=objc), there is shouldn't be a start button. What controller are you using?

**Comment by ILikePlayingGames** [comment]
Yes, I would like the pause button on the controller to work for pausing the game. I’m using a Mad Catz CTRLi.

**Comment by FrederickGeek8** [comment]
What method are you using to install the app? If you are using Cydia Impactor or the Cydia repository, you can drop into [Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and I can send you a private version of iNDS to test the button functionality.

**Comment by ILikePlayingGames** [comment]
I use the build store. I can test it with Cydia impactor though.

**Comment by FrederickGeek8** [comment]
[Message me on Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
