### ISSUE TITLE
Fire Emblem: New Mystery, display issue only in iNDS

### ISSUE THREAD

**Issue by temerianwine** [iNDS-Team/iNDS#90]
A former unsolved post sums it up: https://github.com/WilliamLCobb/iNDS/issues/202

I am trying to play this ROM on my iPod touch. The bottom screen on iNDS seems to not be fully displaying. The ROM itself is fine, I've tested it on my PC. But on iNDS it displays oddly. Looks like perhaps the on screen buttons are causing the trouble? iNDS doesn't have too many settings to mess with to try to fix this, as far as I can see. Anyone have any suggestions?

**Comment by FrederickGeek8** [comment]
I was unable to reproduce this on the current version of iNDS (from this repo).

**Comment by temerianwine** [comment]
I downloaded iNDS from https://iemulators.com/inds

I will try to reinstall and see if that fixes it.

**Comment by temerianwine** [comment]
In my reddit post you can see screenshots: https://www.reddit.com/r/Roms/comments/aie8n5/inds_display_issue_with_fe_new_mystery_rom/

**Comment by temerianwine** [comment]
Just realized something, looks like you opened the game on an iPhone? I'm using an iPod touch and the screen is smaller, maybe that's what it is cutting it off? Not enough display resolution? Just a guess, still haven't gotten to installing the new version yet, will try in a bit.

**Comment by temerianwine** [comment]
Yup, it's working now that I have the newest iNDS. Thanks so much for your responses.
