### ISSUE TITLE
Mario and Luigi bowers inside story 

### ISSUE THREAD

**Issue by cd331** [iNDS-Team/iNDS#92]
Game crashes a soon I start bowers first fight

**Comment by cd331** [comment]
Thanks

**Comment by FrederickGeek8** [comment]
What version of iNDS are you running? I can’t seem to reproduce the crash.

**Comment by realdawg49** [comment]
the game always crashes during the start of bowsers first fight

**Comment by cd331** [comment]
1.9.1

**Comment by FrederickGeek8** [comment]
Can somebody attempt to reproduce this on the latest version of iNDS (1.10.2)? I seem to have no problem getting to the first fight. 

<img src='https://user-images.githubusercontent.com/774597/52894844-9d86ac80-317e-11e9-861c-e23a110bc1e1.jpeg' width=300 />

**Comment by realdawg49** [comment]
no, it’s a little bit after this, it’s when playing as bowser and fighting against midbus

**Comment by FrederickGeek8** [comment]
Ah, okay. Could somebody [send me a message on Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) who could provide me with a save file to test on?

**Comment by realdawg49** [comment]
idk how to do that my guy

**Comment by cd331** [comment]
Me too bro

**Comment by FrederickGeek8** [comment]
I can walk whoever reaches out to me through acquiring the save file.

**Comment by cd331** [comment]
Are u able to receive through email?

**Comment by FrederickGeek8** [comment]
You can try sending it to inds@nerd.net. Please compress (zip, etc) the file.

**Comment by Samgisaninja** [comment]
https://www.dropbox.com/s/47nwoupelwnbniy/4171%20-%20Mario%20%26%20Luigi%20-%20Bowser%27s%20Inside%20Story%20%28USA%29%20%28En%2CFr%2CEs%29.Bug.dsv?dl=0

**Comment by FrederickGeek8** [comment]
@Samgisaninja I'm getting a 404 on that link. If you could update it, that would be ideal.

**Comment by Samgisaninja** [comment]
Sorry about that, here ya go:

https://nofile.io/f/ZqWpraATbBp/4171+-+Mario+%26amp%3B+Luigi+-+Bowser%27s+Inside+Story+%28USA%29+%28En%2CFr%2CEs%29.Bug.dsv

**Comment by Samgisaninja** [comment]
For anyone who sees this in the future: 

I was able to workaround this by sharing the save state file (located in the iNDS app’s documents folder—if you’re jailbroken you can access this with Filza by navigating to /var/mobile/Containers, opening the iNDS folder, then go Documents->battery) to my Mac, changing the extension to .dst, then using desmume to “open state file”, play through the boss fight, “save state file”, change extension back to .dsv, then placing the new dsv file in the Battery folder under the same name as the old dsv file.
