### ISSUE TITLE
Cheat code remains in effect even after deleting the code AND reinstalling iNDS

### ISSUE THREAD

**Issue by temerianwine** [iNDS-Team/iNDS#95]
Playing Fire Emblem Shadow Dragon. For complicated reasons, I wanted to use a code for one very specific scenario to allow one of my units to move again even though she had already done so that turn.

I entered/activate the cheat (which makes it so the enemy turn never happens): 94800004 FFFE0000 121A2A54 00002000 D2000000 00000000

I did what I needed to do, and immediately turned it off.  But the enemy turn never resumed. So I finished the mission hoping it would resolve with the end of the mission, but on the next mission the enemy had no turn either. So I deleted the cheat. Still did not fix it. So I reinstalled iNDS and the enemy still has no turn.

**Comment by FrederickGeek8** [comment]
I'll check it out. Are you using save states or in-game saves?

**Comment by temerianwine** [comment]
I just loaded it up to check on it, and it's magically fixed! Perhaps there was a time expiration? No idea. Regardless, thanks for the reply.
