### ISSUE TITLE
Cover art messed up

### ISSUE THREAD

**Issue by Tikkito** [iNDS-Team/iNDS#99]
The cover art isn’t showing up for any of my games except for 1, Pokémon white 2. [
![a3c46b56-13e7-41c1-bfd3-eecee0023c73](https://user-images.githubusercontent.com/19893545/53700342-2593c580-3dbf-11e9-9f04-a035634c2976.png)
](url)

**Comment by FrederickGeek8** [comment]
Quoting from a previous issue

> The images are loaded from [OpenVGDB](https://github.com/OpenVGDB/OpenVGDB/releases). OpenVGDB provides image links for hashes of ROMs; iNDS downloads and caches these images. I was thinking maybe in the future trying to start a community-based fork of OpenVGDB where people can add entries for unlisted games.

**Comment by FrederickGeek8** [comment]
I have deployed a crowd-sourced ROM addition project for OpenVGDB. I will be adding support for this new service in an upcoming pull request. In other words, by using this link you will be able to match your ROM file to an existing game and get icon support for those games. https://inds.nerd.net/editor/
